### ISSUE TITLE
Actionable dashboard for GitHub organization activities

### ISSUE THREAD

**Issue by moul** [gnolang/benchmarks#10]
We need a one-stop spot to keep tabs on all activity across our repos. We want a way to spot new stuff, stalled issues, first-time contributors, and to whip up reports and changelogs.

A couple of tools might help:
- Vossibility-stack: It's an old friend's project that was pretty cool: https://github.com/icecrime/vossibility-stack.
- Depviz: I used to work on this. It's good at spotting issues and PRs, guessing dependencies, and making graphs, like on our roadmap: https://github.com/gnolang/roadmap. I'm planning to tweak it to help teams match their plans with the unexpected stuff that pops up.

So, we need to hunt down a tool that does what we need or tweak one to suit us. We could possibly lean on GitHub CI, like we do with the roadmap, to keep everything updated while playing nice with GitHub's API limits.

In the long run, this tool could help check on-chain proof of contributions against what's really happening. It could even get a bot to open templated proof of contributions automatically once they're approved and merged.

---

Looking for feedback and tips.

Assigning this issue to @gnolang/devrels for tracking and assistance in implementing this project.

**Comment by waymobetta** [comment]
Currently progressing with a trial of Zenhub; our trial instance can be found [here](https://app.zenhub.com/workspaces/gnolang-64c93882f041431419958a02/board) and will be accessible for testing shortly.

**Comment by waymobetta** [comment]
It seems like Github projects is satisfying this need and is being well-received/well-adopted by the team. Unless there is an additional need, I think we can close this issue.
